// 9fbef606107a605d69c0edbcd8029e5d_SYMPHONY
// routes constants

export const ROUTER_CONSTANTS = {
  digitalPlatform: 'scs',
  gldPlatform: 'symphony',
  inbound: 'inbound',
  outbound: 'outbound',
  warehouse: 'warehouse',
  reports: 'reports',
  billing: 'billing',
  shipments: 'shipments',
  search: 'search',
  itemDetails: 'itemdetails',
  home: 'dashboard',
  account: 'account',
  contact: 'contactus',
  noaccess: 'noaccess',
  admin: 'admin',
  ucp: 'ucp',
  inboundWIP: 'inboundwip',
  outboundWIP: 'outboundwip',
  movement: 'movement',
  freight: 'freight',
  listing: 'listing',
  details: 'details',
  inventory: 'inventory',
  po: 'po',
  exceptions: 'exceptions',
  deliveredExceptions: 'deliveredExceptions',
  brokerage: 'brokerage',
  distributionOrders: 'distributionOrders',
  distributionOrdersListing: 'distributionOrdersListing',
  freightShipments: 'freightShipments',
  freightShipmentsListing: 'freightShipmentsListing',
  financials: 'financials',
  login: 'login',
  movementShipments: 'movementShipments',
  intransitionPage: 'intransition-page',
  cancelledShipments: 'cancelledShipments',
};
